name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: deploy-service
    runs-on: ubuntu-latest # Support GitHub runner: https://github.com/actions/runner-images
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ACR
        # run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
        # run: echo "Ny@12345678" | docker login --username=tiancai@5391368636165801 registry-intl.cn-hangzhou.aliyuncs.com --password-stdin
        run: |
          echo "Ny@12345678" | docker login --username=tiancai@5391368636165801 registry-intl.cn-hangzhou.aliyuncs.com --password-stdin
          docker build -f ./Dockerfile -t g-gateway-svc:latest .
          docker images
          docker tag g-gateway-svc:latest registry-intl.cn-hangzhou.aliyuncs.com/g-services/g-services-repo:g-gateway-svc-20240715.3
          docker push registry-intl.cn-hangzhou.aliyuncs.com/g-services/g-services-repo:g-gateway-svc-20240715.3

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: ${{ secrets.ACR_SERVER }}/your-repo/g-services/g-services-repo:g-gateway-svc:120

      # - name: Verify ACR login
      #   run: docker logout ${{ secrets.ACR_SERVER }}

